#!/usr/bin/env bash

#
# Copyright 2022 Bytedance Inc.
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -eo pipefail

# Export $PRIMUS_HOME
if [ -z "${PRIMUS_HOME}" ]; then
  PRIMUS_HOME="$(cd "$(dirname "$(readlink -f "$0")")"/..; pwd)"
  export PRIMUS_HOME
fi

# Load PRIMUS_ENV
if [ -z "$PRIMUS_ENV_LOADED" ]; then
  export PRIMUS_ENV_LOADED=1

  export PRIMUS_CONF_DIR="${PRIMUS_HOME}/conf"
  echo "set PRIMUS_CONF_DIR to $PRIMUS_CONF_DIR ..."

  export PRIMUS_SBIN_DIR="${PRIMUS_HOME}/sbin"
  echo "set PRIMUS_SBIN_DIR to ${PRIMUS_SBIN_DIR} ..."

  if [ -f "${PRIMUS_CONF_DIR}/primus-env.sh" ]; then
    set -a
    . "${PRIMUS_CONF_DIR}/primus-env.sh"
    set +a
  fi
fi

# Export version
export PRIMUS_VERSION="UNKNOWN"

# Submit the primus job
java -cp "$PRIMUS_HOME"/jars/*:"$CLASSPATH"\
  -Dlog4j2.configurationFile="$PRIMUS_HOME"/conf/log4j2.xml \
  com.bytedance.primus.runtime.kubernetesnative.client.Client \
  --command submit "$@"
