apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.20.15@sha256:6f2d011dffe182bad80b85f6c00e8ca9d86b5b8922cdf433d53575c4c5212248
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /usr/lib/jvm/java-8-openjdk-amd64
        containerPath: /usr/lib/jvm/java-8-openjdk-amd64
        readOnly: true
      - hostPath: /usr/lib/hadoop
        containerPath: /usr/lib/hadoop
        readOnly: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
